spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphql_test
    username: hemis_user
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
